apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: crawl4ai
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkb2NrZXI0emVyb2Nvb2wiLCJwYXNzd29yZCI6ImRja3JfcGF0X0lOdDZuMklpc2h4V2JjX1BZSHBGendrQk9xayIsImF1dGgiOiJaRzlqYTJWeU5IcGxjbTlqYjI5c09tUmphM0pmY0dGMFgwbE9kRFp1TWtscGMyaDRWMkpqWDFCWlNIQkdlbmRyUWs5eGF3PT0iLCJlbWFpbCI6InNhbGlsa2FkYW1AZ21haWwuY29tIn19fQ== 