apiVersion: v1
kind: Service
metadata:
  name: crawl4ai-mcp
  namespace: crawl4ai
spec:
  selector:
    app: crawl4ai-mcp
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP 