apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crawl4ai-mcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salilkadam/crawl4ai-mcp.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: crawl4ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  parameters:
    - name: image.tag
      value: latest
      required: true
    - name: image.repository
      value: docker4zerocool/crawl4ai-mcp
      required: true
    - name: docker.username
      value: docker4zerocool
      required: true
    - name: docker.password
      value: ${DOCKER_PASSWORD}
      required: true 