apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml

commonLabels:
  app.kubernetes.io/name: crawl4ai-mcp
  app.kubernetes.io/part-of: crawl4ai

images:
  - name: docker4zerocool/crawl4ai-mcp
    newName: docker4zerocool/crawl4ai-mcp
    newTag: latest 