apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: crawl4ai
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "${DOCKER_AUTH}"
        }
      }
    } 